name: safe_xerox
description: A secure printing solution with cloud integration and temporary accounts.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  http: ^1.1.0
  mobile_scanner: ^5.1.0
  supabase_flutter: ^2.0.0
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
